### ISSUE TITLE
Thoth as github actions

### ISSUE THREAD

**Issue by pventuzelo** [FuzzingLabs/thoth#102]
I got asked if we can create thoth github actions, it's a good idea, here is some example of usage:

- generate graphs and update project docs automatically.
- run analyzer for security vulnerabilities
- etc.

**Comment by pventuzelo** [comment]
example by kakarot: https://github.com/gaetbout/kakarot/blob/main/.github/workflows/thoth.yml

**Comment by EvolveArt** [comment]
https://github.com/EvolveArt/thoth-action/tree/v0.1.0
For now it just updates docs w/ callgraphs but I'll also add static analyzer option, could be cool to have it generate a SARIF file just like [amarna](https://github.com/crytic/amarna-action) is doing.

Looks like there is a permission issue when trying to run it on one of my repos tho.

Would be great to add the ability to just run `thoth local .` on any repo, it would compile all the contracts it finds and run thoth on them.

**Comment by pventuzelo** [comment]
I need to check for SARIF file because we are not using the Cairo source file but either the cairo assembly/bytecode or the sierra file.

Do you know how to solve the permission issue?

Thoth is not compiling any contract, that's why we are only dealing with artifact compilation files (cairo bytecode or sierra)
