### ISSUE TITLE
Sym exec instructions in README are not clear

### ISSUE THREAD

**Issue by ggballas** [FuzzingLabs/thoth#110]
1. No explanation on `-variables` flag. what is it? is it used to constrain function variables? why can't they just be constrained with the `-constraint` flag?

2. Can constraints have `!=`, `>`, or `<` ? Not clear from instructions. If not, then this is definitely a suggestion from me.

Thanks for a great tool either way:)

**Comment by Rog3rSm1th** [comment]
Hello,

For the first point the `-variables` flag is used to set the value of a variable to a specific value (for example when a variable is assigned using a function call and it's value is unknown). 

Concerning the second point for now it is only possible to define constraints using the `==` operator.

Thanks for your feedback and suggestions it is very helpful!

**Comment by ggballas** [comment]
okay, thank you for the answer.

about the `-variables` flag, let's say I have this decompiled line of code:
```
...
let (v551_res) = read()
...
```

what would be the difference between setting `v551_res` using the `-constraint` flag vs. using the `-variables` flag?

**Comment by pventuzelo** [comment]
Should be good now with the new version "0.7.0" ;)
