### ISSUE TITLE
Support for Cairo 1.0

### ISSUE THREAD

**Issue by cwkang1998** [FuzzingLabs/thoth#124]
Is there any plans for thoth to support the upcoming Cairo 1.0 update? Would like to know the general plan around migrating from the 0.10.4 -> 1.0, and would love to contribute to it if there's such plans.

Thanks for your work on thoth!

**Comment by pventuzelo** [comment]
Hey,
Thoth supports Cairo bytecode (casm) directly and is not affected by Cairo language modification.
It's also supporting Sierra files now so if you compile Cairo 1.0 contract you can provide the sierra file to Thoth instead of the JSON artifact.

You're welcome ;)

**Comment by trangnv** [comment]
I tried to run `thoth-sierra -f ./target/dev/hello_starknet.sierra -d   `
But face the error `./target/dev/hello_starknet.sierra is not a valid sierra file`.
Any idea how to fix it?
Thank you
