### ISSUE TITLE
[DECOMP] reconstruct function call args 

### ISSUE THREAD

**Issue by pventuzelo** [FuzzingLabs/thoth#36]
based on current disassembly:

![image](https://user-images.githubusercontent.com/9038181/179195596-139cc76c-d1c8-4212-978d-3cb1536b6757.png)

![image](https://user-images.githubusercontent.com/9038181/179195754-edae62e6-8d27-448a-8133-2aa465207718.png)

we should be able to associate args to ASSERT_EQ opcode:

![image](https://user-images.githubusercontent.com/9038181/179195715-61442ebe-8d03-42f8-8530-f28b968e3b3a.png)

**Comment by raefko** [comment]
Done with the releae 0.2.0
![image](https://user-images.githubusercontent.com/8091541/187689342-2063d0b7-a97e-4d83-96a4-2be41c7795ea.png)
