### ISSUE TITLE
[CFG] support direct CALL to label & relative JUMP

### ISSUE THREAD

**Issue by pventuzelo** [FuzzingLabs/thoth#43]
Direct CALL inside the same function `call rel 123` are possible (recursive function), it needs to be considered as a jump.

Same idea with relative JUMP e.g. `jump rel 7`

For the moment we ignore them

![image](https://user-images.githubusercontent.com/9038181/179355033-eb8d775b-1b7d-427c-8a82-7f9bca76e67d.png)

**Comment by Rog3rSm1th** [comment]
Fixed with https://github.com/FuzzingLabs/thoth/commit/e1820dde7fd1bbe9af2f150f3191de01831b9405, it is now possible to jump in the middle of a basic block (fallthrough edge).
