### ISSUE TITLE
ASSERT_EQ - IF/ELSE AP assign before if

### ISSUE THREAD

**Issue by raefko** [FuzzingLabs/thoth#74]
In this example
![image](https://user-images.githubusercontent.com/8091541/186846622-311c19f5-6bb8-49c1-80b7-e55f371f3271.png)

We have 
`[AP-2] = [AP] + [AP-1]`
We should have : 
`[AP] = [AP-2]-[AP-1]`
Because [AP] is not assigned yet.

**Comment by Rog3rSm1th** [comment]
Fixed with [a5c3785ed8d6a35868bc169f07e40e889087fd2e](https://github.com/FuzzingLabs/thoth/commit/05bc78b029868dc59c18e874707c6e93614eefaf)
