### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by SebFuzzingLabs** [FuzzingLabs/thoth#87]
We have a ValueError if we try to decompile `test.cairo`
For this code (`test.cairo`):
![image](https://user-images.githubusercontent.com/93118369/193801248-c35d5a45-1b79-4aae-b347-aaf6889b1c21.png)
We get this error:
![image](https://user-images.githubusercontent.com/93118369/193801411-50bb5d17-1420-4102-9f88-a0a137d9b648.png)
(using: `thoth -f test.json -d`)

But the dissas works.

[ValueError.zip](https://github.com/FuzzingLabs/thoth/files/9705257/ValueError.zip)

**Comment by raefko** [comment]
#88
