### ISSUE TITLE
AssertionError: Unsupported instruction

### ISSUE THREAD

**Issue by SebFuzzingLabs** [FuzzingLabs/thoth#89]
We have an AssertionError when we try to disass or to decompile `test.cairo`.
For this code (`test.cairo`):
![image](https://user-images.githubusercontent.com/93118369/193830603-577c4d35-22a9-4d55-bcf9-94e492f7be48.png)

We get this error:
![image](https://user-images.githubusercontent.com/93118369/193831337-3cb0d898-3ad2-4420-8436-839e14a87098.png)
(using: `thoth -f test.json`)

And we get this error:
![image](https://user-images.githubusercontent.com/93118369/193831454-d3bbaead-2061-4e57-acdf-3e2bd0af7ab3.png)
(using: `thoth -f test.json -d`)

[AssertionError.zip](https://github.com/FuzzingLabs/thoth/files/9707234/AssertionError.zip)

**Comment by pventuzelo** [comment]
Fixed
